### ISSUE TITLE
Inconsistency between GMT file names and msigdb names

### ISSUE THREAD

**Issue by GMFranceschini** [DavisLaboratory/msigdbR#2]
Hi, thank you for developing this package. I think it is very useful.
I noticed that there are some inconsistencies between the names of GMT files from (http://www.gsea-msigdb.org/gsea/msigdb/genesets.jsp?collection=GO:BP) and the names in the DB. For example: 

GMT: "GOBP_MATURATION_OF_5_8S_RRNA"
DB:"GOBP_MATURATION_OF_5.8S_RRNA"

GMT:"GOMF_VOLTAGE_GATED_ION_CHANNEL_ACTIVITY"
DB:"GOMF_VOLTAGE-GATED_ION_CHANNEL_ACTIVITY"

I don't know if this is intentional or not, I just noticed that it is causing quite some troubles in the integration with previous analyses based on GMT files and I hope my report is useful.

**Comment by bhuvad** [comment]
Hi @GMFranceschini,

I am sorry for not having seen this issue earlier! The reason this is happening is that there is a difference between the original MSigDB GO sets and our GO sets. The online MSigDB significantly filters the full collection of the GO as described in the [MSigDB 7.0 release notes](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/MSigDB_v7.0_Release_Notes). Many large and small gene-sets as well as those that share a large number of genes are filtered out. This is done to produce optimal input for the GSEA algorithm; however, it can result in loss of potentially interesting processes. To avoid filtering, we rebuild the GO and re-create the gene-set collection for Human and Mouse without omitting any gene-sets. This allows the user more flexibility in determining their own filters. Methods such as `limma::fry` and our newly developed method [vissE](https://bioconductor.org/packages/release/bioc/html/vissE.html) which exploit information redundancy in databases greatly benefit from the additional information.

The reason the names differ is that MSigDB gets rid of special characters while we retained the original names as they were. Thank you for pointing this out! We will aim to follow their naming convention so that the gene-sets that are common between our version and the online MSigDB match up.

Cheers,
Dharmesh
